config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do
    resources :entries do
      resources :meals, :exercises
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_one :exercise
  has_one :meal
  accepts_nested_attributes_for :meal
  accepts_nested_attributes_for :exercise
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :entry
end

app/models/meal.rb
class Meal < ApplicationRecord

  belongs_to :entry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries
  has_many :meals, through: :entries
  has_many :exercises, through: :entries

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def show
    @user = current_user
    @entry = Entry.find(params[:id])
  end
  
  def new
    @entry = Entry.new
    # @meal = Meal.find(params[:meal_id])
    # @exercise = Exercise.find(params[:exercise_id])
  end

  def create
    @user = User.find(params[:user_id])
    @entry = @user.entries.new()
    if @entry.save
      redirect_to user_entry_path(@user, @entry)
    else
      flash[:notice] = "NO dice bro"
    end
  end





private


end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
    @exercise =Exercise.new
    @user = current_user
    @entry = Entry.find(params[:entry_id])
    respond_to do |format|
      format.html { redirect_to user_entry_path(@user, @entry) }
      format.js
    end
  end
  def create
    @exercise = Exercise.create(exercise_params)
      respond_to do |format|
      format.html { redirect_to user_entry_path() }
      format.js
    end
  end

private
  def exercise_params
    params.require(:exercise).permit(:name, :calorie_count)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
    @user = current_user
    @entry = Entry.find(params[:entry_id])
    respond_to do |format|
      format.html { redirect_to user_entry_path(@user, @entry) }
      format.js
    end
  end

  def create


    @entry = Entry.find(params[:entry_id])

    # @meal = @entry.meal.create(:meal_attributes => {:entry_id => @entry.id})
    @meal = Meal.new(meal_params)
    @meal.entry = @entry
    @meal.save
    binding.pry
    respond_to do |format|
      format.html { redirect_to user_entry_path(@user, @entry) }
      format.js
    end
  end

private
  def meal_params
    params.require(:meal).permit(:name, :calorie_count)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:email, :avatar, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    render :profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/entries/show.html.erb
<h1>New Entry</h1><br>

<div id="results">

</div>

<%= link_to "New meal entry", new_user_entry_meal_path(@user, @entry), remote: true, id: :new_meal_link %><br>
<%= link_to "New exercise entry", new_user_entry_exercise_path(@user, @entry), remote: true, id: :new_exercise_link %>

app/views/exercises/_exercise.html.erb
<ul class="exercise">
  <li><%= @exercise.name %></li>
  <li><%= @exercise.calorie_count %></li>
</ul>

app/views/exercises/_form.html.erb
<%= form_for([@user, @entry, @exercise], remote: true) do |f| %>
  <%= f.label :name, "Exercise" %><br>
  <%= f.text_field :name %><br>
  <%= f.label :calorie_count, "Calories burned" %><br>
  <%= f.text_field :calorie_count %><br>
  <%= f.submit "Add" %>
<% end %>

app/views/exercises/create.js.erb
$("#new_exercise").hide();
$('#results').append("<%= j render @exercise %>")
$('#new_entry').fadeIn(1000);

app/views/exercises/new.html.erb
<%= render "form"%>

app/views/exercises/new.js.erb
$("#new_exercise_link").fadeOut(500).after("<%= j render 'form' %>");

app/views/home/index.html.erb
<h1>Hey this is the home page</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EpicTracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li role="separator" class="divider"></li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", new_user_session_path %></li>

        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      </ul>
    <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpiTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_for([@user, @entry, @meal], remote: true) do |f| %>
  <%= f.label :name, "Meal" %><br>
  <%= f.text_field :name %><br>
  <%= f.label :calorie_count %><br>
  <%= f.text_field :calorie_count %><br>
  <%= f.submit "Add" %>
<% end %>

app/views/meals/_meal.html.erb
<ul class="meal">
  <li><%= @meal.name %></li>
  <li><%= @meal.calorie_count %></li>
</ul>

app/views/meals/create.js.erb
$("#new_meal").hide();
$('#results').append("<%= j render @meal %>");

app/views/meals/new.html.erb
<%= render 'form' %>

app/views/meals/new.js.erb
$('#new_meal_link').fadeOut(500).after('<%= j render ("form") %>');

app/views/users/profile.html.erb
<h2>Profile</h2>

<%= @user.email %><br>

<%= image_tag @user.avatar.url(:medium) %>

<div class="calendar">
  <%= month_calendar do |date| %>
    <%= date %> <br>
    <%= button_to user_entries_path(@user) do %>
      <strong>Add new Entry</strong</>
    <% end %>
  <% end %>

</div>